export enum TRACKED_ENTITY_ATTRIBUTES {
	EPISODE_ID = "qMMZr6Jqccr",
	DEVICE_IMEI = "HE8z2yxSJ74",
}

export enum DATA_ELEMENTS {
	DEVICE_HEALTH = "QH0OjHcBBpO",
	BATTERY_HEALTH = "Vc6c6OjvvHO",
	DOSAGE_TIME = "FOHv6pUjBjv",
	DEVICE_SIGNAL = "oHBM5fsFc6p",
}
