export enum TRACKED_ENTITY_ATTRIBUTES {}

export enum SHARED_ATTRIBUTES {}

export enum DATA_ELEMENTS {
	DEVICE_HEALTH = "QH0OjHcBBpO",
	BATTERY_HEALTH = "Vc6c6OjvvHO",
	DOSAGE_TIME = "FOHv6pUjBjv",
	DEVICE_SIGNAL = "oHBM5fsFc6p",
}

export enum PROGRAM_STAGES {}
