name: Build
on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Sets up a Node.js environment, with yarn as the package manager
      - uses: actions/setup-node@v3
        with:
          node-version: 16.20.1
          cache: yarn
      - name: Install JS dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
